pothosware/SoapySDR

- apps/SoapySDRProbe.cpp
- apps/SoapySDRUtil.cpp
- cmake/SoapySDRConfig.cmake
- include/SoapySDR/Device.h
- include/SoapySDR/Device.hpp
- lib/Device.cpp
- lib/Factory.cpp
- lib/Modules.in.cpp
- lib/Registry.cpp
- lib/TypeHelpers.hpp
- python/SoapySDR.i
* use C++11 internally to simplify code
* use std::mutex inside factory calls
* update API docs about thread safety
* remove python factory mutex (in core library now)
* provide C++11 flags to submodules
* resolves #74
> C++11 support

- include/SoapySDR/Logger.h
- include/SoapySDR/Logger.hpp
- lib/LoggerC.cpp
By only logging to stderr by default, command-line tools can be more easily written using SoapySDR which write their own output to stdout. Otherwise, stdout becomes a mixture of SoapySDR logging and the tool's output.
Consistently logging to stderr also makes redirecting logging more straightforward, `./foo 2>/tmp/log` will save all of the logging to /tmp/log, instead of only the higher severity messages, as the lower severity messages go to stdout. `./foo 2>/tmp/log-stderr >/tmp/log-stdout` would capture both, but then the high and low severity messages would be separated, necessitating something like `./foo >/tmp/log 2>&1` to combine both stdout and stderr into one file. This gets 
complicated quickly, my 2¢ I think it's better to at least by default log messages only to …
> Change SoapySDR logger to only use stderr by default

- debian/control
Works fine with both swig 2 and 3 (from debian testing).
> debian: allow any swig >= 2.0.12

- CMakeLists.txt
- Changelog.txt
- apps/SoapySDRUtil.cpp
- include/SoapySDR/Version.h
- include/SoapySDR/Version.hpp
- lib/Version.in.cpp
- lib/VersionC.cpp
* added a getLibVersion() to query the library version with build info
* added SOAPY_SDR_API_VERSION for compile time checks
* getAPIVersion() now queries a string version of SOAPY_SDR_API_VERSION
* added general documentation about version numbering
@andreasbombe let me know if this satisfies the issue, I will go with this for 0.5.1 then.
> Added SoapySDR_getLibVersion() and SOAPY_SDR_API_VERSION

- Changelog.txt
- appveyor.yml
- include/SoapySDR/Device.h
- include/SoapySDR/Version.h
- lib/DeviceC.cpp
- lib/ErrorHelpers.hpp
- lib/FactoryC.cpp
This PR represents additional try/catch blocks for C API device calls. This causes graceful returns with error message set (vs std::terminate when the uncaught exception throws in C). The API was not properly set up to provide error return codes. We are not introducing any C API changes in this commit. This is a fix commit for 0.5 series; so the following was done for existing calls:
* All errors thrown set SoapySDRDevice_lastError()
* API calls that returned points will return NULL on error
* API calls that return PODs return -1 or NAN (whatever fits)
* API calls that return void set the error, but there is nothing to show
* Because error cannot be determined for all return types, a ``int SoapySDRDevice_lastStatus()`` is provided to determine the error state of the last device API call. …
> Additional try/catch for C API

- CMakeLists.txt
- Changelog.txt
- lib/Modules.in.cpp
Merging into maint for an eventual 0.5.4 release tag
* Added SOAPY_SDR_ROOT_ENV to cmake and root path to control the environment variable used to locate the root in a dynamically re-located file systems -- in this case a snap install that uses the SNAP environment variable
* Modified SOAPY_SDR_ROOT to match style and to deal with empty default, because CMAKE_INSTALL_PREFIX is set to empty in snap build
> Snappy support

- Changelog.txt
- lib/Factory.cpp
Only the result of enumerate() is used to key the devices in the factory table. This ensures an accurate table regardless of optional arguments passed in by the user.
* Resolves https://github.com/pothosware/SoapySDR/issues/116
> Fix device table keying

- .travis.yml
Travis CI mysteriously broke the python2 unit tests. Could be a travis environment change for python executable paths. Open this PR to push commits until its resolved.
> fix travis python test - explicit python2 executable path

- lib/ConverterRegistry.cpp
- lib/DefaultConverters.cpp
Fix for loading modules linked to another copy of the library: avoids double loading of static loads by doing it manually somewhere else in the API.
> Late load converters

- lib/DeviceC.cpp
- lib/LoggerC.cpp
- lib/TypeHelpers.hpp
- lib/TypesC.cpp
* Type conversions get calloc fail checks and others
* added other general error checks
* Added type helper for string to character array
* use std::copy where applicable
* throw bad_alloc on fail (caught by try/catch in c wrappers)
> addtional checks for bad allocs - c only wrappers

- Changelog.txt
- include/SoapySDR/Device.h
- include/SoapySDR/Device.hpp
- lib/Factory.cpp
- lib/FactoryC.cpp
- lib/Modules.in.cpp
- lib/Registry.cpp
- lib/TypeHelpers.hpp
- python/SoapySDR.i
* Device::make, Device::unmake, and Device::enumerate can be called in from multiple threads
* Convenience calls Device::make(argslist) and Device::unmake(devicelist) to parallelize creating an array of devices from an array of handles (and cleanup)
> support parallel device construction

- lib/TypeHelpers.hpp
the "value" field of the SoapySDRArgInfo type was not being copied from C++ land to C land, causing segfaults in code that used it.  This adds the missing copy operation.
> copying missing `value` field in SoapySDRArgInfo C wrapper

- CMakeLists.txt
- Changelog.txt
- apps/CMakeLists.txt
- cmake/Modules/SoapySDRConfig.cmake
- cmake/Modules/SoapySDRUtil.cmake
- lib/CMakeLists.txt
- python/CMakeLists.txt
- python3/CMakeLists.txt
* encapsulated include/linker/flags on targets
* project config exports a target (just link to SoapySDR)
* Resolves https://github.com/pothosware/SoapySDR/issues/152
* moved cmake requirements up to v3
> Update to modern cmake

- include/SoapySDR/Logger.h
- include/SoapySDR/Logger.hpp
- lib/LoggerC.cpp
- python/SoapySDR.i
This extends the ability to set a log message handler, present in the C/C++ API, to the Python API.  The motivation is to provide a means for Python code to be aware of fault conditions that don't trigger the return of an error code or the throwing of an exception.  An example of such a fault is a failure to calibrate the SDR.  See issue #201.
In addition, the default log handler can now be restored from both APIs by passing `None`/`nullptr` to `registerLogHandler()`.
> Provide Python registerLogHandler() support

- python/apps/MeasureDelay.py
- python/apps/SimpleSiggen.py
- python/apps/soapy_log_handle.py
Update the two example Python applications
MeasureDelay.py and SimpleSiggen.py have been extended and updated.
- fix up integer handling (MeasureDelay.py failed to run under Python3)
- replace the deprecated optparse module with argparse
- replace numpy's tofile() calls with the platform independent numpy.save() 
- renamed command line options from camelCase to more conventional hyphen delimited style (e.g. "--txChan" to "--tx-chan")
- added --debug and --halt-on-error options
- use a python coded log handler function
> Python examples

- include/SoapySDR/Device.h
- lib/DeviceC.cpp
Backwards compatible change to C API for SoapySDRDevice_setupStream() to return stream pointer to be consistent with other APIs. The stream is returned as a pointer with null on error.
```
- SOAPY_SDR_API int SoapySDRDevice_setupStream(SoapySDRDevice *device, SoapySDRStream **stream
+ SOAPY_SDR_API SoapySDRStream *SoapySDRDevice_setupStream(SoapySDRDevice *device
```
> C setup stream API change

- docs/Doxyfile.in
- include/SoapySDR/Device.hpp
- include/SoapySDR/Types.h
- include/SoapySDR/Types.hpp
- python/SoapySDR.i
- tests/CMakeLists.txt
- tests/TestConvertTypes.cpp
Improvements to C++ and Python API for read/writeSettings and readSensor:
* added defines SOAPY_SDR_TRUE and SOAPY_SDR_FALSE for commonly used boolean settings
* added converters for driver implementations to use SettingToString, StringToSetting
* Device class overloads based on template type of setting/sensor
API use in c++
```
- d->writeSetting("FOO", std::to_string(1 << 13));
+ d->writeSetting("FOO", 1 << 13);
- auto v = std::stoi(d->readSetting("FOO"));
+ auto v = d->readSetting<int>("FOO");       #type cannot be inferred
```
API use in python
```
- d.writeSetting("FOO", str(1 << 13))
+ d.writeSetting("FOO", 1 << 13)
- v = int(d.readSetting("FOO"))
+ v = d.readSetting("FOO")       #type is inferred as int
```
Potential driver implementation changes:
```
SoapySDR::ArgInfoList …
```
> Templated settings

- apps/SoapyRateTest.cpp
- apps/SoapySDRProbe.cpp
- apps/SoapySDRUtil.cpp
This adds sensor readings and a watch command to SoapySDRUtil.
E.g. `SoapySDRUtil --probe="driver=plutosdr"` will follow "Peripheral summary" / "Sensors:" with a table of current sensors readings.
Also e.g. the new `SoapySDRUtil --watch="driver=plutosdr"` will output a table of sensors readings every second.
> Add sensor readings and watch command

- python/get_python_lib.py
In the never ending python install path whack-a-mole, site.getsitepackages() sometimes does not exist
* resolves https://github.com/pothosware/SoapySDR/issues/239
* @gasparka are you able to test this change on your setup?
> try/except for site.getsitepackages()

- apps/SoapySDRUtil.cpp
Make it easy to specify serial for the args which is the best way to identify a device when there are many.
> util - added --serial option

- include/SoapySDR/Device.h
- include/SoapySDR/Device.hpp
- lib/Device.cpp
- lib/DeviceC.cpp
As requested in #277
> I would like to include the ref clock API for setReferenceClockRate/getReferenceClockRate/getReferenceClockRates. Can I get the PR for just that change?
> adding reference clock to the clocking API

- Changelog.txt
- apps/SoapySDRUtil.cpp
- include/SoapySDR/Modules.h
- include/SoapySDR/Modules.hpp
- include/SoapySDR/Version.h
- lib/Modules.in.cpp
- lib/ModulesC.cpp
Added unload modules API to unload all modules and cleanup internal data structures.
Should be called manually on application exit.
* closes https://github.com/pothosware/SoapySDR/issues/280
> Unload modules

- CMakeLists.txt
Needed as with newer CMake versions, SWIG is very noisy at build time due to these new policies not being enabled. Example output with policies not enabled:
```
CMake Warning (dev) at /Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.19/Modules/UseSWIG.cmake:661 (message):
Policy CMP0078 is not set: UseSWIG generates standard target names.  Run
"cmake --help-policy CMP0078" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
Call Stack (most recent call first):
ExternalLibs/SoapySDR/python/CMakeLists.txt:160 (SWIG_ADD_LIBRARY)
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at /Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.19/Modules/UseSWIG.cmake:513 (message):
Policy CMP0086 is …
```
> Add new CMake policies to build if present

- buildkite/build.sh
- include/SoapySDR/Device.h
- include/SoapySDR/Device.hpp
Found via `codespell -q 3 -L devicec,dne,inout,ue`
> Fix misc. typos

- python3/CMakeLists.txt
From UseSWIG:
Changed in version 3.15: Alternate library name (set with the OUTPUT_NAME property, for example)
will be passed on to Python and CSharp wrapper libraries
The issue:
This seems to cause an extra underscrore in the output name which breaks
the imports and .i file. The fix is to set the name conditionally
Notes:
This should not affect users building python modules from the default
python/ directory. Its only the special python3/ extra directory.
> python3 - change OUTPUT_NAME in newer versions of cmake

- include/SoapySDR/Types.hpp
- tests/TestConvertTypes.cpp
Used to special case "0" and "0.0", ignoring the many other (beautiful
in their own right) ways to specify 0 numerals.
No reason to be be that tricky and implement stuff ourselves – C++11 has
safe converters that everyone is familiar with.
> Types: When converting strings to bool, be as unsurprising as possible

- include/SoapySDR/Device.h
Just a minor fix to the comment to indicate that the return value is just
a single range in each case, not a list. Of course that should be evident
from the signature, but still.
> capi: doc: Clarify GainRange is not a list

- lib/LoggerC.cpp
- lib/Modules.in.cpp
rather than rely on msvc macros, use cmake checks for windows header and missing API calls
* closes https://github.com/pothosware/SoapySDR/pull/318
> windows: robustify the windows ifdefs

- lib/CMakeLists.txt
CMake allows for `CMAKE_INSTALL_LIB_DIR` to be absolute: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html
Some linux distributions (at least NixOS) set this path as absolute by default, which causes problems with module-loading, as the constructed search path, concatenated from `SoapySDR::getRootPath()` and `CMAKE_INSTALL_LIB_DIR`, contains the common path-prefix twice.
I would thus suggest to use `CMAKE_INSTALL_LIB_DIR` unchanged, if it is absolute (starts with `/`).
This should have no impact on Windows targeted builds - but that's just a guess, as I'm not using Windows.
A better solution would probably be to use [std::filesystem::operator/](https://en.cppreference.com/w/cpp/filesystem/path/operator_slash). But this is only available from C++17 onwards.
> fix module search paths, if CMAKE_INSTALL_LIB_DIR is absolute

- apps/SoapyRateTest.cpp
- apps/SoapySDRUtil.cpp
This adds a `--format[=CS16]` option to the rate testing. The default is to use the native sample format, as before.
> Add sample format option to rate test

- CMakeLists.txt
- lib/CMakeLists.txt
The `target_compile_options` on `SoapySDR PUBLIC` (i.e. `INTERFACE_COMPILE_OPTIONS` via `SoapySDRExport.cmake` in dependent projects) needs `-Wnon-virtual-dtor` conditional for only C++ compilers, otherwise C-projects will get
```
error: command-line option ‘-Wnon-virtual-dtor’ is valid for C++/ObjC++ but not for C
```
> Fix Wnon-virtual-dtor to conditional

- include/SoapySDR/Device.h
Fixes a minor typo in doxygen annotations. S.a. https://www.doxygen.nl/manual/commands.html#cmdparam
> Fix minor doxygen annotation typo

- include/SoapySDR/Types.hpp
* Fixes non-deterministic behavior in LuaJIT bindings
* Closes https://github.com/pothosware/SoapySDR/issues/365
> ArgInfo: added initialized value for type field

- lib/TypeHelpers.hpp
report options count rather than optionNames count to C binding
fixes https://github.com/pothosware/SoapySDR/issues/377
> Fix toArgInfo() options count with empty optionNames in C binding

- .gitignore
Because the default build instructions recommend an in-tree build output directory, this change adds the directory name to `.gitignore` so that the git tree is not marked as dirty after running the build instructions.
> Add `.gitignore` to exclude `build/`

- CMakeLists.txt
I am currently contribugint to MSYS by adding SoapySDR as a package. In the process, I found that CMake treats MSYS as WIN32 and changes CMake files installation paths...
This proposes a fix to avoid having to patch source for MSYS distribution.
More info on https://github.com/msys2/MINGW-packages/pull/17446.
> Treat MSYS CMake installation paths as Unix

- lib/SoapySDR.in.pc
See #352 for details around the bug
> pkg-config: Use cmake full paths instead of manually concatenating

- lib/Modules.in.cpp
Closes #430
This fixes module symbols polluting the namespace on MacOS. This change is already the default on Linux.
> Fix SoapySDR::loadModule dlopen to hide symbols using RTLD_LOCAL

- CMakeLists.txt
Based on @Biswa96 review on https://github.com/pothosware/SoapySDR/pull/413, a better fix is proposed.
Sorry about the double PR! :)
> Treat MinGW CMake installation paths as Unix instead of MSYS

- include/SoapySDR/Types.h
- lib/TypeHelpers.hpp
The SoapySDRArgInfo struct has an optional `optionNames` array. However, the client has no way of knowing whether these labels were filled by the SDR driver or are left uninitialized. Allocating and zeroing the array is more foolproof, in my opinion, and does not break the ABI.
See: https://github.com/pothosware/SoapySDR/issues/377#issuecomment-2480732739
> TypeHelpers: pre-callocate optionNames even if no names are provided

- .github/workflows/ci.yml
MacOS 11 and 12 runners are not supported anymore. Switches to 13, 14, and 15 runners.
Also removes the `test_luajit` conditional as the test works on all runners now.
> Update GitHub Actions for MacOS runners

- docs/Doxyfile.in
- include/SoapySDR/Device.h
- include/SoapySDR/Device.hpp
- swig/csharp/docs/Doxyfile.in
Removes Doxygen settings that are obsolete and were default anyway to reduce clutter.
Drops
- `TCL_SUBST`
- `CLANG_ASSISTED_PARSING`
- `CLANG_OPTIONS`
- `COLS_IN_ALPHA_INDEX`
- `FORMULA_TRANSPARENT`
- `LATEX_SOURCE_CODE`
- `LATEX_TIMESTAMP`
- `RTF_SOURCE_CODE`
- `DOCBOOK_PROGRAMLISTING`
- `PERL_PATH`
- `CLASS_DIAGRAMS`
- `MSCGEN_PATH`
- `DOT_FONTNAME`
- `DOT_FONTSIZE`
- `DOT_TRANSPARENT`
Does not drop
- `HTML_TIMESTAMP`
which has been replaced by `TIMESTAMP` in release 1.9.7 (release date 18-05-2023)  but is still honored (with 1.11.1).
Closes #451
> Update Doxygen config to remove obsolete settings

- swig/python/cmake/FindPython/Support.cmake
Update `cmake_policy` to new `3.12` format for `3.14` compat which is already used by policies in main CMakeLists.txt.
We could possibly use `3.15` as `max` and remove the [`CMP0094`](https://cmake.org/cmake/help/latest/policy/CMP0094.html) setting but I have not tested that.
This reduces the warnings when building with swig to just the LuaJIT warning.
S.a. #450
> Update cmake_policy in swig for CMake 3.12 compat
