pothosware/SoapySDR

CMakeLists.txt, Changelog.txt, cmake/SoapySDRConfig.cmake, include/SoapySDR/Device.h, include/SoapySDR/Device.hpp, include/SoapySDR/Version.h, lib/Device.cpp, lib/DeviceC.cpp, lib/TypeHelpers.hpp, python/SoapySDR.i
* Resolves https://github.com/pothosware/SoapySDR/issues/92
=> Bulk read and write registers calls

Changelog.txt, include/SoapySDR/Types.h, include/SoapySDR/Types.hpp, lib/Factory.cpp, lib/Types.cpp, lib/TypesC.cpp, tests/CMakeLists.txt, tests/TestKwargsMarkup.cpp
* Resolves https://github.com/pothosware/SoapySDR/issues/87
=> Added Kwargs type to/from markup string

apps/CMakeLists.txt, apps/SoapyRateTest.cpp, apps/SoapySDRUtil.cpp
Test sustained receive and transmit rates, num overflows/underflows.
=> Add rate test to command line util

.travis.yml
Testing travis hooks for osx builds with a PR.
=> enable osx builds in travis ci

include/SoapySDR/Device.h, include/SoapySDR/Device.hpp
Clarify documentation with info from #111.
=> Documentation tweaks

.travis.yml
OSX python paths are screwy again. Using a PR to test fixes. Sorry about the noise...
=> travis: fix osx build in travis

Changelog.txt, include/SoapySDR/Types.h, lib/TypesC.cpp
* resolves https://github.com/pothosware/SoapySDR/issues/173
* resolves #175
=> Added error handling and return code to SoapySDRKwargs_set()

include/SoapySDR/Device.h, include/SoapySDR/Device.hpp, lib/Device.cpp, lib/DeviceC.cpp
create merge for option to use automatic set iq balance
=> calls to set iq balance mode automatic

include/SoapySDR/Types.h, lib/DeviceC.cpp, lib/ErrorHelpers.hpp, lib/FactoryC.cpp, lib/ModulesC.cpp, lib/TypeHelpers.hpp, lib/TypesC.cpp
this exposes the free() needed for resources returned by the C API calls
=> added SoapySDR_free for the C bindings

include/SoapySDR/Device.h, include/SoapySDR/Device.hpp, lib/Device.cpp, lib/DeviceC.cpp
=> adding access to native device handle

Changelog.txt, include/SoapySDR/Device.h, include/SoapySDR/Device.hpp, include/SoapySDR/Version.h, lib/Factory.cpp, lib/FactoryC.cpp, lib/TypeHelpers.hpp
=> Device: added parallel make() function that takes in string vector

Changelog.txt, python/CMakeLists.txt, python/SoapySDR.in.i, python3/CMakeLists.txt
* Closes https://github.com/pothosware/SoapySDR/issues/300
=> python: perform ABI check on import, raise exception on mismatch

cmake/Modules/SoapySDRUtil.cmake, lib/CMakeLists.txt
* non platform specific properties that control flags if available
=> cmake: use properties to set visibility hidden

include/SoapySDR/Constants.h
See https://github.com/pothosware/SoapyBladeRF/issues/31#issuecomment-531077320
=> added flags for SDR specific data

luajit/init.in.lua
I'm sure I can script this generation...
=> luajit: added new user flags

include/SoapySDR/Device.hpp, include/SoapySDR/Version.h
=> Device: fix templated readSetting() constness

.github/workflows/ci.yml, .github/workflows/cross-ci.yml, luajit/Lib.lua
* Linux: GCC 11-12, Clang 13-14
* Windows: MSVC 17 (VS2022), MinGW
* Added FreeBSD testing
* Added various Linux+Windows cross-compile tests via Dockcross
=> ci: cleanup, support more platforms

swig/csharp/assembly/Stream.cs, swig/csharp/tests/TestStreamingAPI.cs
* Closes https://github.com/pothosware/SoapySDR/issues/391
=> csharp: fixed Stream.Deactivate logic bug

python/CMakeLists.txt, python/SoapySDR.in.i, python/doctypes.i
* Manually added docstrings for manually written Python functions
* If SWIG 4.0+, use new feature to auto-generate docstrings from Doxygen
=> Added Python docstrings, depending on SWIG version

swig/python/get_python_lib.py
This switches to using sysconfig from distutils, which is necessary for Python 3.12+ since distutils is deprecated and has been removed.
It is necessary to specify the install scheme when a prefix other than the Python default is used so that changes to the default scheme made by distributions (e.g. Debian, Fedora) do not produce an incorrect Python installation directory. For example, Debian patches the default scheme to prepend the path with '/local', but if a user specifies a prefix of '/usr/local', then the path using the default scheme would be '/usr/local/local/...' with a duplicated 'local' directory. Specifying an unmodified install scheme fixes that. This comes from experience in having to do a similar change with GNU Radio.
I tried this with the conda-forge package on top of the …
=> Remove deprecated use of distutils, fix for Python 3.12+

.github/workflows/ci.yml, swig/python/CMakeLists.txt, swig/python/get_python2_lib.py
Fix ci after the python lib update for older python, we should drop 2 though...
=> use old get python lib for v2
